Sdes functions
mateustito/cifras pull request #7
Opened 2019-10-02 14:40 UTC by mateustito

- Conversão texto para binário e vice versa
- Permutação Inicial
- XOR

2019-10-02 14:44 UTC, luiscarlossf commented on s-des.py
> +        binario += bin(ord(i))[2::] + ' '
Por que esse espaço no fim?

2019-10-02 14:48 UTC, mateustito commented on s-des.py
> +        binario += bin(ord(i))[2::] + ' '
Dar um espaço entre as letras do texto que estão sendo convertidas

2019-10-02 14:51 UTC, luiscarlossf commented on s-des.py
> +    result.append(output)
Não seria mais conveniente retornar só o 'output'?

2019-10-02 14:51 UTC, luiscarlossf commented on s-des.py
> +        binario += bin(ord(i))[2::] + ' '
Por que desse espaço em branco no final?

2019-10-02 21:36 UTC, mateustito commented on s-des.py
> +        binario += bin(ord(i))[2::] + ' '
separar as letras que foram convertidas para binario

2019-10-02 21:41 UTC, mateustito reviewed
ok

2019-10-02 21:41 UTC, mateustito commented on s-des.py
> +    result.append(output)
Eh mesmo. Irei simplificar :)

2019-10-03 00:36 UTC, luiscarlossf commented on s-des.py
> +        binario += bin(ord(i))[2::] + ' '
Tipo, 213 vai ser : 10 1 11 ? Se for, não precisa desse espaço

2019-10-03 03:04 UTC, mateustito commented on s-des.py
> +        binario += bin(ord(i))[2::] + ' '
Isso, vai colocar o resultado separado. Com os dígitos/caracteres separados podemos aplicar a conversão inversa bin to text, pq tudo junto não encontrei uma forma para isso.

2019-10-03 03:09 UTC, luiscarlossf commented on s-des.py
> +        binario += bin(ord(i))[2::] + ' '
Não faz muito sentido, não.

2019-10-03 03:10 UTC, victrck approved these changes

2019-10-03 03:28 UTC, victrck requested changes
Tenta mudar a função text_to_bin, creio que retornando uma lista seja mais interessante, é a minha opnião nao me leve a mal....

2019-10-03 03:40 UTC, mateustito reviewed
Lista ok

2019-10-03 03:40 UTC, mateustito commented on s-des.py
> +        binario += bin(ord(i))[2::] + ' '
Entao vamos na metodologia da lista

2019-10-03 22:30 UTC, closed without merging